version: '3'
services:
  db:
    image: postgres:14.5-alpine
    ports:
      - '5432:5432'
    volumes:
      - .postgres:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/scripts:/scripts
    environment:
      POSTGRES_PASSWORD: secret
    tty: true
    stdin_open: true
  app:
    build:
      context: ./app
      dockerfile: containers/development/Dockerfile
    command: /bin/bash -c "mix deps.get && iex -S mix phx.server"
    ports:
      - '4000:4000'
    volumes:
      - ./app:/app
    environment:
      - DOCKER_POSTGRES_HOST=db
      - ERL_AFLAGS=-kernel shell_history enabled
    depends_on:
      - db
    tty: true
    stdin_open: true
  mgt:
    build:
      context: ./mgt
      dockerfile: containers/development/Dockerfile
    command: /bin/sh -c "yarn install && yarn serve"
    ports:
      - '8000:8000'
    volumes:
      - ./mgt:/mgt
      - /mgt/node_modules
